# Generated by Django 4.2 on 2025-06-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_checkin_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirm_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确定时间'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, '待确定'), (1, '已确定'), (2, '进行中'), (3, '已完成'), (4, '已取消'), (5, '已过期')], default=0, verbose_name='预约状态'),
        ),
    ]
