# Generated by Django 4.2 on 2025-06-17 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False, verbose_name='评价ID')),
                ('rating', models.IntegerField(verbose_name='评分（1-5分）')),
                ('content', models.CharField(blank=True, max_length=1000, null=True, verbose_name='评价内容')),
                ('images', models.TextField(blank=True, null=True, verbose_name='评价图片URL（JSON格式）')),
                ('reply_content', models.CharField(blank=True, max_length=500, null=True, verbose_name='管理员回复内容')),
                ('reply_time', models.DateTimeField(blank=True, null=True, verbose_name='回复时间')),
                ('status', models.IntegerField(choices=[(1, '已发布'), (2, '已删除'), (3, '已隐藏')], default=1, verbose_name='评价状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking', verbose_name='预约记录')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility', verbose_name='场馆')),
            ],
            options={
                'verbose_name': '评价记录',
                'verbose_name_plural': '评价记录',
                'db_table': 'reviews',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rating'], name='idx_review_rating'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['status'], name='idx_review_status'),
        ),
    ]
