# Generated by Django 4.2 on 2025-06-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False, verbose_name='聊天ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='会话ID')),
                ('user_message', models.TextField(verbose_name='用户消息')),
                ('ai_response', models.TextField(verbose_name='AI回复')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'AI聊天历史',
                'verbose_name_plural': 'AI聊天历史',
                'db_table': 'chat_history',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='城市名称')),
                ('temperature', models.IntegerField(verbose_name='温度')),
                ('weather', models.CharField(max_length=50, verbose_name='天气状况')),
                ('icon', models.CharField(max_length=50, verbose_name='天气图标')),
                ('humidity', models.IntegerField(verbose_name='湿度')),
                ('wind_speed', models.IntegerField(verbose_name='风速')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '天气数据',
                'verbose_name_plural': '天气数据',
                'db_table': 'weather_data',
            },
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['city'], name='weather_dat_city_96d319_idx'),
        ),
        migrations.AddIndex(
            model_name='weatherdata',
            index=models.Index(fields=['update_time'], name='weather_dat_update__7cdf79_idx'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['session_id'], name='chat_histor_session_37a41e_idx'),
        ),
        migrations.AddIndex(
            model_name='chathistory',
            index=models.Index(fields=['create_time'], name='chat_histor_create__51099c_idx'),
        ),
    ]
