# Generated by Django 4.2 on 2025-06-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('notice_id', models.AutoField(primary_key=True, serialize=False, verbose_name='公告ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('notice_type', models.IntegerField(choices=[(1, '系统公告'), (2, '营业时间'), (3, '活动通知'), (4, '维护通知')], default=1, verbose_name='公告类型')),
                ('priority', models.IntegerField(choices=[(1, '普通'), (2, '重要'), (3, '紧急')], default=1, verbose_name='优先级')),
                ('start_time', models.DateTimeField(verbose_name='开始显示时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束显示时间')),
                ('is_published', models.BooleanField(default=True, verbose_name='发布状态')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('view_count', models.IntegerField(default=0, verbose_name='查看次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '公告信息',
                'verbose_name_plural': '公告信息',
                'db_table': 'notices',
                'ordering': ['-is_top', '-priority', '-create_time'],
            },
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['notice_type'], name='notices_notice__ba5e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['is_published'], name='notices_is_publ_4f2cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['start_time'], name='notices_start_t_4805e9_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['end_time'], name='notices_end_tim_766e31_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['is_top'], name='notices_is_top_c216f7_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['priority'], name='notices_priorit_e97978_idx'),
        ),
    ]
