# Generated by Django 4.2 on 2025-06-17 06:33

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('account_id', models.AutoField(primary_key=True, serialize=False, verbose_name='账户ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('real_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='真实姓名')),
                ('id_card', models.CharField(blank=True, max_length=20, null=True, verbose_name='身份证号')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('avatar', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像URL')),
                ('register_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '禁用')], default=1, verbose_name='账户状态')),
                ('user_type', models.IntegerField(choices=[(1, '普通用户'), (2, '管理员')], default=1, verbose_name='用户类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户账户',
                'verbose_name_plural': '用户账户',
                'db_table': 'accounts',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False, verbose_name='日志ID')),
                ('operation_type', models.CharField(max_length=50, verbose_name='操作类型')),
                ('operation_desc', models.CharField(blank=True, max_length=255, null=True, verbose_name='操作描述')),
                ('request_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='请求URL')),
                ('request_method', models.CharField(blank=True, max_length=10, null=True, verbose_name='请求方法')),
                ('request_params', models.TextField(blank=True, null=True, verbose_name='请求参数')),
                ('response_status', models.IntegerField(blank=True, null=True, verbose_name='响应状态码')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='用户代理')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operation_logs',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False, verbose_name='配置ID')),
                ('config_key', models.CharField(max_length=100, unique=True, verbose_name='配置键名')),
                ('config_value', models.TextField(blank=True, null=True, verbose_name='配置值')),
                ('config_type', models.CharField(choices=[('string', '字符串'), ('number', '数字'), ('boolean', '布尔值'), ('json', 'JSON')], default='string', max_length=20, verbose_name='配置类型')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='配置描述')),
                ('is_public', models.BooleanField(default=False, verbose_name='是否公开')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'system_configs',
            },
        ),
        migrations.AddIndex(
            model_name='systemconfig',
            index=models.Index(fields=['config_key'], name='system_conf_config__a14607_idx'),
        ),
        migrations.AddIndex(
            model_name='systemconfig',
            index=models.Index(fields=['is_public'], name='system_conf_is_publ_1e8b69_idx'),
        ),
        migrations.AddField(
            model_name='operationlog',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户'),
        ),
        migrations.AddField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['account'], name='operation_l_account_a92f10_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['operation_type'], name='operation_l_operati_01172f_idx'),
        ),
        migrations.AddIndex(
            model_name='operationlog',
            index=models.Index(fields=['create_time'], name='operation_l_create__1e9190_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['username'], name='accounts_usernam_cab5ec_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['phone'], name='accounts_phone_715c93_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user_type'], name='accounts_user_ty_fc004a_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['status'], name='accounts_status_8b566b_idx'),
        ),
    ]
