# Generated by Django 4.2 on 2025-06-17 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False, verbose_name='场馆ID')),
                ('facility_name', models.CharField(max_length=100, verbose_name='场馆名称')),
                ('location', models.CharField(max_length=255, verbose_name='场馆位置')),
                ('capacity', models.IntegerField(verbose_name='容纳人数')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='面积（平方米）')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='场馆图片URL')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价（元/小时）')),
                ('description', models.TextField(blank=True, null=True, verbose_name='场馆描述')),
                ('opening_hours', models.CharField(default='06:00-22:00', max_length=100, verbose_name='营业时间')),
                ('advance_booking_days', models.IntegerField(default=7, verbose_name='可提前预约天数')),
                ('min_booking_duration', models.IntegerField(default=1, verbose_name='最小预约时长（小时）')),
                ('max_booking_duration', models.IntegerField(default=4, verbose_name='最大预约时长（小时）')),
                ('status', models.IntegerField(choices=[(1, '可用'), (2, '维护中'), (3, '已关闭')], default=1, verbose_name='场馆状态')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序顺序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '场馆信息',
                'verbose_name_plural': '场馆信息',
                'db_table': 'facilities',
                'ordering': ['sort_order', 'facility_id'],
            },
        ),
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='类型ID')),
                ('type_name', models.CharField(max_length=50, unique=True, verbose_name='类型名称')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='类型图标')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='类型描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '场馆类型',
                'verbose_name_plural': '场馆类型',
                'db_table': 'facility_types',
                'ordering': ['sort_order', 'type_id'],
            },
        ),
        migrations.AddIndex(
            model_name='facilitytype',
            index=models.Index(fields=['sort_order'], name='facility_ty_sort_or_43a5a4_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitytype',
            index=models.Index(fields=['is_active'], name='facility_ty_is_acti_ddc06b_idx'),
        ),
        migrations.AddField(
            model_name='facility',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facilitytype', verbose_name='场馆类型'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['type'], name='facilities_type_id_a0b02b_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['status'], name='facilities_status_bc7cf5_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['sort_order'], name='facilities_sort_or_18537d_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['price'], name='facilities_price_9e3309_idx'),
        ),
    ]
