# Generated by Django 4.2 on 2025-06-17 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False, verbose_name='预约ID')),
                ('booking_date', models.DateField(verbose_name='预约日期')),
                ('start_time', models.TimeField(verbose_name='开始时间')),
                ('end_time', models.TimeField(verbose_name='结束时间')),
                ('person_count', models.IntegerField(default=1, verbose_name='预约人数')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总金额')),
                ('status', models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已完成'), (3, '已取消'), (4, '已过期')], default=0, verbose_name='预约状态')),
                ('remark', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注信息')),
                ('is_member_used', models.BooleanField(default=False, verbose_name='是否使用会员权益（已停用）')),
                ('cancel_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='取消原因')),
                ('cancel_time', models.DateTimeField(blank=True, null=True, verbose_name='取消时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility', verbose_name='场馆')),
            ],
            options={
                'verbose_name': '预约记录',
                'verbose_name_plural': '预约记录',
                'db_table': 'bookings',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_date'], name='idx_booking_date'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='idx_booking_status'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['facility', 'booking_date', 'start_time', 'end_time'], name='idx_booking_facility_datetime'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('facility', 'booking_date', 'start_time', 'end_time'), name='unique_facility_datetime'),
        ),
    ]
