# Generated by Django 4.2 on 2025-06-17 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='booking',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='booking',
            name='purpose',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='预约目的'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(0, '未开始'), (1, '待确认'), (2, '进行中'), (3, '已完成'), (4, '已取消'), (5, '已过期')], default=1, verbose_name='预约状态'),
        ),
    ]
