# Generated by Django 4.2 on 2025-06-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_contact_name_booking_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkin_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='签到时间'),
        ),
    ]
