# Generated by Django 4.2 on 2025-06-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_add_facility_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='facility_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='场馆名称'),
        ),
    ]
